#!/bin/sh

git clone https://git.suckless.org/st && cd st

# Apply a patch to support scrolling
curl -O https://st.suckless.org/patches/scrollback/st-scrollback-ringbuffer-0.8.5.diff
git apply st-scrollback-ringbuffer-0.8.5.diff

make clean st && cp ../config.h config.h

doas make install

