#!/bin/sh

cd $1

git status > /dev/null || exit 1

git remote update > /dev/null
git status -uno | grep "is up to date" && exit 0

git pull --quiet || exit 2

makepkg --syncdeps --rmdeps --clean --install

echo "Done!"
